Switch beta to head of current dev (kodi 20)
flathub/tv.kodi.Kodi pull request #132
Opened 2021-12-06 23:17 UTC by razzeee

2021-12-18 04:47 UTC, wsnipex requested changes
let's try to get inputstream.adaptive fixed.

2021-12-18 04:47 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
> +      "commit": "0b2715a282f3726d089fae592c46efd425aa5b49"
```suggestion
      "commit": "785d2b10542f84417189409044b1165d47df23e2"
```

2021-12-18 04:47 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
> +      "url": "https://github.com/peak3d/inputstream.adaptive",
```suggestion
      "url": "https://github.com/xbmc/inputstream.adaptive",
```

2021-12-18 04:47 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
> +  "config-opts": ["-DBUILD_TESTING=OFF"],
```suggestion
  "config-opts": ["-DBUILD_TESTING=OFF", "-DENABLE_INTERNAL_BENTO4=ON"],
```

2021-12-18 04:47 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
> +  "modules": [
bento4 can be removed here, including all the patches

2021-12-19 05:35 UTC, wsnipex reviewed
untested: see suggestion for how to hopefully fix IA/bento4.

Otherwise feel free to revert to  what you had before.

2021-12-19 05:35 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
>          }
```suggestion
        },
        {
              "type": "archive",
              "url": "https://github.com/axiomatic-systems/Bento4/archive/refs/tags/v1.6.0-639.tar.gz",
              "sha256": "9f3eb912207d7ed9c1e6e05315083404b32a11f8aacd604a9b2bdcb10bf79eb9",
              "dest": "bento4_src",
              "dest-filename:" bento4.tar.gz"
```

2021-12-19 05:35 UTC, wsnipex commented on addons/inputstream.adaptive/inputstream.adaptive.json
> +        "-DENABLE_INTERNAL_BENTO4=ON"
```suggestion
        "-DENABLE_INTERNAL_BENTO4=ON",
        "-DBENTO4_URL=bento4_src"
```

2021-12-20 11:33 UTC, wsnipex approved these changes

2021-12-20 13:18 UTC, merged

2021-12-21 15:05 UTC, hfiguiere commented
this MR talks about `beta` but was merged on `master` aka `stable`. So now the stable flatpak has a pre-release version

2021-12-21 15:15 UTC, wsnipex commented
yep, we're trying to get this resolved